---
- hosts: all
  connection: ssh
  user: niri
  become: yes

  tasks:
    - yum:
        name: ['httpd','docker','tree']
        state: installed
      when: ansible_os_family == "RedHat"
      notify: n

    - yum:
        name: apache2
        state: installed
      when: ansible_os_family == "Debian"
      notify: n1
       

  handlers:
    - name: n

      service:
        name: httpd
        state: started

      service:
        name: docker
        state: started

    - name: n1
      service:
        name: apache2
        state: started
